export default {
    root: {
        layout: {
            title: "Create Next App",
            description: "Generated by create next app",
        },
        page: {
            title: "next template",
            author: "By Matin Rezaei",
        },
    },
} as const;
