export default {
    root: {
        title: "Create Next App",
        description: "Generated by create next app",
        heading: "next template",
        author: "By Matin Rezaei",
    },
} as const;
