export default {
    root: {
        layout: {
            title: "Create Next App",
            description: "Generated by create next app",
        },
        page: {
            title: "this is home page",
        },
    },
} as const;
